### ISSUE TITLE
Fix tagging/release scheme

### ISSUE THREAD

**Issue by vapurrmaid** [vapurrmaid/bpm#30]
## Tags

- @vapurrmaid/bpm@<version>
- @vapurrmaid/bpm-react-app@<version>

## Tasks

- [x] replace old tags with new ones
- [x] update GH releases
- [x] update release/automation scripts
